---
abstract: 'Mojolicious Plugin for RESTful operations'
author:
  - 'Abhishek Shende <abhishekisnot@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-REST
requires:
  Lingua::EN::Inflect: 0
  Mojolicious: 0
resources:
  homepage: https://github.com/abhishekisnot/Mojolicious-Plugin-REST
  repository: https://github.com/abhishekisnot/Mojolicious-Plugin-REST.git
version: 0.003
